version: '3.9'

services:
  semantic-sql:
    build: ./semantic-sql
    container_name: semantic-sql
    depends_on:
      - postgres-db          
    ports:
      - "8888:8888"
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_DB=semanticdb
      - POSTGRES_USER=semantic_user
      - POSTGRES_PASSWORD=semantic_pass
    volumes:
      - ./data_persistent:/workspace
      - .:/app
    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root --notebook-dir=/workspace

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: semanticdb
      POSTGRES_USER: semantic_user
      POSTGRES_PASSWORD: semantic_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./entrypoint_db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U semantic_user -d semanticdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
